version: "2.0"
services:
  "tws":
    image: alekna/ib-tws
    shm_size: "512mb"
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"
    logging:
      driver: "none"
    ports:
      - "5901:5900"
      - "7497:7497"
