name: Publish docker image

on:
  push:
    branches:
      - master

env:
    USERNAME: alekna
    REPO: ib-tws

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag image

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u $USERNAME --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=$USERNAME/$REPO
          VERSION=latest

          docker tag image $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
